# Generated by Django 2.1 on 2018-08-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(verbose_name='Event Date')),
            ],
        ),
    ]
